### ISSUE TITLE
build-API revision

### ISSUE THREAD

**Issue by Rollmops** [sealor/junkie#11]
Junkie should expose a clear and transparent API for the Context.build(...) function.

1. Proposal:

**Passing classes**

- `build(type)` -> instance
- `build(*types)` -> tuple of instances
- `build(**types)` -> dict of instances with keys

**Passing strings**

- `build(str)` -> instance
- `build(*str)` -> dict of instances with keys

**Passing mixed values**

- `build(*str_or_types)` -> tuple of instances

**Note:**

If you have a list as an input you can do:

`build(*list)`

If you have a dict as an input you can do:

`build(**dict)`

**Comment by Rollmops** [comment]
Thats a good idea... I like that 😁

**Comment by sealor** [comment]
This general `build()` method could call the following more specific methods:

```python
@contextmanager
def build_dict(self):
    pass

@contextmanager
def build_list(self):
    pass

@contextmanager
def build_tuple(self):
    pass

@contextmanager
def build_element(self):
    pass
```

**Comment by sealor** [comment]
I realised that "Arbitrary Argument Lists" are implemented as `tuple`s  in Python:
https://docs.python.org/3/tutorial/controlflow.html#arbitrary-argument-lists

To be consistent we should handle an argument list as `tuple` instead of `list`.

API:
```
@overload
def build_tuple(self, target_tuple: Tuple[Union[str, type, Callable]]) -> Tuple[object]:
    pass

@overload
def build_tuple(self, *target_args: Union[str, type, Callable]) -> Tuple[object]:
    pass

@contextmanager
def build_tuple(self, *args):
    pass
```
Usage:
```
with context.build("var1", MyApp) as (instance1, instance2):
    self.assertEqual("abc", instance1)
    self.assertEqual(MyApp, type(instance2))
```
